apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thenovadiary
  name: thenovadiary
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thenovadiary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thenovadiary
    spec:
      containers:
        - image: krisnova/thenovadiary:latest
          imagePullPolicy: Always
          name: thenovadiary
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30